### ISSUE TITLE
Sample for registers.out

### ISSUE THREAD

**Issue by cojocar** [brandon-rhodes/trace-memory-access#1]
Hi,

do you have a sample for `registers.out`? Or how could I generate it?

Thanks,
Lucian

**Comment by cojocar** [comment]
The `${arch}_regnum` enum from `gdb/${arch}-tdep.h` contains this information.

**Comment by brandon-rhodes** [comment]
I suspect that it parsed the output from GDB's command `info registers`, once you have a process running under GDB.
